# Generated by Django 3.2.16 on 2023-11-18 04:16

import django.db.models.deletion
from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Избранные рецепты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='Имя ингредиента'
                    ),
                ),
                (
                    'measurement_unit',
                    models.CharField(
                        max_length=5, verbose_name='Единица измерения'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200, verbose_name='Название рецепта'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to='recipes/', verbose_name='Изображение'
                    ),
                ),
                ('text', models.TextField(verbose_name='Описание рецепта')),
                (
                    'cooking_time',
                    models.IntegerField(
                        validators=[recipes.validators.validate_time],
                        verbose_name='Время на приготовление в минутах',
                    ),
                ),
                (
                    'pub_date',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name='Дата и время добавления',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Ингредиенты рецептов',
            },
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Теги рецептов',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='Название тега'
                    ),
                ),
                (
                    'color',
                    models.CharField(max_length=16, verbose_name='Цвет'),
                ),
                ('slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ShopingCart',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'recipe',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cart',
                        to='recipes.recipe',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Список покупок',
            },
        ),
    ]
