# Generated by Django 3.2.16 on 2024-01-21 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribeuser',
            name='users_subscribeuser_prevent_self_follow',
        ),
    ]
