# Generated by Django 3.2.16 on 2024-01-21 05:12

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'users',
            '0002_remove_subscribeuser_users_subscribeuser_prevent_self_follow',
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribeuser',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('user', django.db.models.expressions.F('author')),
                    _negated=True,
                ),
                name='users_subscribeuser_prevent_self_follow',
            ),
        ),
    ]
