# Generated by Django 3.2.16 on 2024-01-21 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'users',
            '0003_subscribeuser_users_subscribeuser_prevent_self_follow',
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribeuser',
            name='unique_following_follower',
        ),
        migrations.AlterUniqueTogether(
            name='subscribeuser',
            unique_together={('user', 'author')},
        ),
    ]
