# Generated by Django 3.2.16 on 2024-01-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20240121_0819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribeuser',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subscribeuser',
            constraint=models.UniqueConstraint(
                fields=('user', 'author'), name='unique_following_follower'
            ),
        ),
    ]
